galaxy_info:
  author: Aleksand Ponomarev
  description: Role to install and enable Apache service on server.
  company: Epam Learning
  license: BSD
  min_ansible_version: 2.9
  platforms:
  - name: Centos
    versions:
    - 8
  galaxy_tags: []
dependencies: []