galaxy_info:
  author: Aleksandr Ponomarev
  description: "An Ansible role for setting up Vsftpd"
  company: Epam Learning
  license: BSD
  min_ansible_version: 2.9
  platforms:
  - name: Centos
    versions:
    - 8
  galaxy_tags: []
dependencies: []